on: 
  push:
    branches:
      - main
name: 🚀 Deploy website on push

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3

    - name: Set up Node.js version
      uses: actions/setup-node@v3
      with:
          node-version: '18.x'
      
    - name: 🔨 Build Project
      run: |
       run: |
          npm install
          npm install react-pro-sidebar@0.7.1
    - name: Build React app with warnings allowed
      run: npm run build
      env:
          CI: false  # Set CI to false during the build step

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
<<<<<<< HEAD
         server: ftp.startza.in
         username: timesheetreact@startza.in
         password: Start@12345# cBZ8D&l[OEIQ
         local-dir: ./build/
         server-dir: /home3/startza/public_html/timesheetreact  # Update this line
         protocol: ftp
         port: 21

=======
        server: ${{ secrets.ftp_server }}
        username: ${{ secrets.ftp_username }}
        password: ${{ secrets.ftp_password }}
    
>>>>>>> e1d8b57a56cc51b2ce96a91d4d689da12dc0c2f8
        
