# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - timesheet-react

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: npm install
        run: |
          npm install
          npm install react-pro-sidebar@0.7.1
      - name: Build React app with warnings allowed
        run: npm run build
        env:
          CI: false  # Set CI to false during the build step

      - name: Zip Release
        uses: TheDoctor0/zip-release@0.7.6
        with:
          filename: release.zip
          path: ./build/*
          
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: release.zip
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v2
        with:
          name: node-app
          path: release.zip

      - name: Deploy using lftp
        run: |
          HOST="yftp.startza.in" # Change this to your cPanel domain
          USER="timesheetreact@startza.in"        # Change this to your cPanel username
          PASS="Start@12345#"        # Change this to your cPanel password
          REMOTE_PATH="/home3/startza/public_html/timesheetreact"     # Change this to the path where you want to deploy

          lftp -d -c "open -u $USER,$PASS $HOST; mirror -e -R -v -x .git -x .github -x .gitignore -x deploy.yml -x README.md -x .gitattributes $GITHUB_WORKSPACE/ $REMOTE_PATH/" || exit 1

     
