# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - react-timesheet-azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      

      - name: npm install, build, and test
        run: 
          npm install
          npm install react-pro-sidebar@0.7.1
          npm run build --if-present
          npm run test --if-present

      - name: Set CI environment variable
        run: 
         echo "CI=false" >> $GITHUB_ENV
      
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: .

 jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Clean up temp folders
        run: |
          sudo rm -rf /tmp/*
          sudo rm -rf /var/tmp/*

      - name: Remove unnecessary files
        run: |
          find . -type f -exec du -h {} + | sort -rh | awk '$1 > 100M {print $2}' | xargs sudo rm -f

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set up .NET
        uses: actions/setup-dotnet@v7
        with:
          dotnet-version: '6.x'

      - name: Build and publish
        run: |
          dotnet publish -c Release -o out

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'react-timesheet-azure'
          slot-name: 'Production'
          package: ./out
