name: Build and deploy Node.js app to Azure Web App - react-timesheet-azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '14.x'

      - name: Check if node_modules exists
        run: |
          if [ -d "node_modules" ]; then
            echo "Node modules already installed."
          else
            npm install
          fi

      - name: npm run build and test
        run: |
          npm run build --if-present
          npm run test --if-present

      - name: Set CI environment variable
        run: |
          echo "CI=false" >> $GITHUB_ENV

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app
      
      - name: Clean up unnecessary files
        run: |
          rm -rf node_modules
          rm -f package-lock.json
          # Add other cleanup commands as needed

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'react-timesheet-azure'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_688802788B9E4F9CB070931725C1E4C5 }}
